### ISSUE TITLE
Limit and offset clauses fail the syntax validation

### ISSUE THREAD

**Issue by oreh** [TwoLaid/python-sqlparser#6]
Sql string, "select * from table0 limit 100", is taken as syntax invalid. Is this expected?

**Comment by TwoLaid** [comment]
Are you using the correct vendor? Not every SQL dialect accepts `LIMIT`.
When creating a `Parser` object, you can specify a dialect with the `vendor` argument. You can either use the number or the `EVendor` enum.

A quick check of a couple of dialects:


    import sqlparser
    from sqlparser import EVendor

    query = """select * from table0 limit 100"""

    parser = sqlparser.Parser(vendor=EVendor.mssql)
    print("Vendor mssql (0): %d" % parser.check_syntax(query))

    parser = sqlparser.Parser(vendor=EVendor.oracle)
    print("Vendor oracle (1): %d" % parser.check_syntax(query))

    parser = sqlparser.Parser(vendor=EVendor.mysql)
    print("Vendor mysql (2): %d" % parser.check_syntax(query))

    parser = sqlparser.Parser(vendor=EVendor.db2)
    print("Vendor db2 (5): %d" % parser.check_syntax(query))

    parser = sqlparser.Parser(vendor=EVendor.postgresql)
    print("Vendor postgresql (8): %d" % parser.check_syntax(query))

Results in the following console output:

```
Vendor mssql (0): 1
Vendor oracle (1): 1
Vendor mysql (2): 0
Vendor db2 (5): 1
Vendor postgresql (8): 0
```

I am not sure why it is invalid for the `mysql` vendor, because it's definitely valid MySQL syntax.. but that is something you should ask the customer support of the underlying C library over @ http://sqlparser.com/

**Comment by oreh** [comment]
Awesome! I did not even notice that vendor is selectable. Thanks a lot for explain this!
